# Generated by Django 5.1.14 on 2026-02-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0075_alter_botmediarequest_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemeetbotlogin',
            name='auth_protocol',
            field=models.CharField(choices=[('saml', 'SAML'), ('oidc', 'OIDC')], default='saml', max_length=10),
        ),
        migrations.AddField(
            model_name='googlemeetbotlogin',
            name='oidc_client_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='googlemeetbotlogin',
            name='oidc_client_secret_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
