# Generated by Django 5.1.14 on 2026-02-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0076_googlemeetbotlogin_auth_protocol_and_more'),
        ('bots', '0077_alter_participantevent_event_type_and_more'),
    ]

    operations = [
    ]
